/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface ToSignerInput {
  owner: string
  entity: string
}
export function createQrCode(toSignerInput: ToSignerInput): string
